name = "js-unknown"
targets = ["web", "nodejs"]
dependencies = ["std"]

[[package-set.extends]]
url = "https://raw.githubusercontent.com/ditto-lang/package-sets/63a9aeba5035ed57385801ec8f63208477c84255/packages.toml"
sha256 = "638d99c65aed99d35c7dbe61050925949164107865bedb3c49a2ba27cae6ad8a"