name = "js-unknown"
targets = ["web", "nodejs"]
dependencies = ["std"]

[package-set.packages.std]
github = { owner = "ditto-lang", repo = "std" }
revision = "867969bd505be704f8bb45bb3de6d984beea4c38"
sha256 = "18d7a27c3379977ac5e8ddec9a0f7390845028076d85affbe4aa5da2b82555ce"
