name = "js-unknown"
targets = ["web", "nodejs"]
dependencies = ["std"]

[package-set.packages.std]
github = { owner = "ditto-lang", repo = "std" }
revision = "2b6ba19a726530f43c63a770c1742056b01a5fbf"
sha256 = "dc6c3ddd4ac794a67bdd304d73b414be68e5f6d734f24a9bd0a7b4d133f4e864"
